server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    # 表示是否将自己注册进 Eureka Server，默认为 true
    # 消费者不提供服务，可不将其注册进入 注册中心
    register-with-eureka: false
    # 是否从 Eureka Server 抓取已有的注册信息，默认为 true。单节点无所谓，集群必须设置为 true 才能配合 Ribbon 使用负载均衡。
    fetch-registry: true
    service-url:
      # defaultZone: http://localhost:7001/eureka/ # 单机版
      defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/ # 集群版

# 设置 feign 客户端超时时间（OpenFeign默认支持Ribbon）
ribbon:
  ConnectTimeout: 5000 # 建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间。
  ReadTimeout: 5000  # 建立连接后从服务器读取到可用资源所用的时间。

logging:
  level:
    top.dj.feign.FeignService: debug # feign日志以什么级别监控哪个接口
