server:
  port: 8002

spring:
  application:
    name: cloud-payment-service # 服务别名
  datasource: # mysql8.0
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/spring_cloud?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&rewriteBatchedStatements=true
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  client:
    # 表示是否将自己注册进 Eureka Server，默认为 true
    register-with-eureka: true
    # 是否从 Eureka Server 抓取已有的注册信息，默认为 true。单节点无所谓，集群必须设置为 true 才能配合 Ribbon 使用负载均衡。
    fetch-registry: true
    service-url:
      # defaultZone: http://localhost:7001/eureka # 单机版
      defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/ # 集群版
  instance:
    instance-id: payment8002
    prefer-ip-address: true # 访问路可以显示IP地址

mybatis:
  mapper-locations: classpath*:mapper/**/*Mapper.xml # 配置mapper的扫描，找到所有的mapper.xml映射文件
  type-aliases-package: top.dj.entity # 所有实体entity别名类所在包

