server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com # eureka服务端的实例名称
  client:
    register-with-eureka: false # false表示不向注册中心注册自己
    fetch-registry: false # false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务。
    service-url:
      # 设置与 Eureka Server 交互的地址查询服务和注册服务都需要依赖这个地址。
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ # 单机模式（指向自己的 Eureka）
      # defaultZone: http://eureka7002.com:7002/eureka/ # 集群模式（指向其他的 Eureka）

  # server:
    # 关闭自我保护机制，保证不可用的服务被及时剔除
    # enable-self-preservation: false # Eureka 的自我保护机制默认为 true（默认开启了自我保护）
    # eviction-interval-timer-in-ms: 2000 # 剔除期限为 2 秒

